### ISSUE TITLE
Indent enters inifinite loop

### ISSUE THREAD

**Issue by tomekowal** [elixir-lang/emacs-elixir#129]
I have this code in my `macors.exs` file:

    defmodule Unless do^
    end

`^` is position of my cursor. I am hitting enter and emacs hangs with 100% processor usage. I tried `debug-on-quit` and it gave me this:

    Debugger entered--returning value: nil
      looking-at("^[        ]*end$")
      elixir-mode-indent-line()
      indent-according-to-mode()

Package installed from melpa: http://melpa-stable.milkbox.net. I am using emacs24.3 on OSX.

**Comment by zkat** [comment]
Hey. I seem to be getting this too. Any update on this?

**Comment by tonini** [comment]
@tomekowal @zkat could you guys please test that behavior again with the current master branch? 

Thanks :+1:

**Comment by tomekowal** [comment]
I should have checked, what version of package did I install back then to compare the behaviour. Currently I can't even replicate the bug, because I removed the package, when it didn't work for me.

But now I checked it out from repository and both master branch and tag v2.2.2 work for me without this bug, so I think, that the issue might be closed.

Thank you for your work! :)

**Comment by tonini** [comment]
Great, thanks a lot of testing it :-)

Tomasz Kowal <notifications@github.com> schrieb am Fr., 22. Mai 2015 21:18:
