### ISSUE TITLE
require/import ordering problem

### ISSUE THREAD

**Issue by fremontmj** [elixir-lang/emacs-elixir#164]
If I have this:

```elixir
defmodule A do
  require Record
  import B
```

I get the error message: "module B is not loaded and could not be found"

If, instead, I do this:

```elixir
defmodule A do
  import B
  require Record
```

I get no such message.  

In both cases Elixir in fact does the right thing.

Best,

Mike

**Comment by tonini** [comment]
Hi @fremontmj 

Where you get this error message? By Elixir itself?

I think we can't help you here, because thats an Elixir programming language output and have nothing to do with the Emacs `elixir-mode`.

Please ask this question to the #elixir-lang irc channel or stackoverflow.

Thanks

**Comment by fremontmj** [comment]
Oh, you know, I think the message is from Flycheck. It shows up at the bottom of the buffer, under the modeline.  Flycheck is checking via Elixir, so I think you're right, I'll check over at elixir-lang.

Weird, since my code seems to work regardless of the order.

**Comment by rranelli** [comment]
Flycheck has this kind of issues in other languages too (ELisp being one of them). I don't know the details, but I've learned to ignore these "{module,file} could not be found".

I think this issue can be closed.
