### ISSUE TITLE
Indenting too far over when invoking evil-open-above and evil-open-below

### ISSUE THREAD

**Issue by robmerrell** [elixir-lang/emacs-elixir#165]
I'm an evil-mode user and when I invoke either evil-open-above ("O" in normal mode) or evil-open-below ("o" in normal mode) the resulting indentation level is inline with the last enclosing keyword rather than just indenting two spaces. I have attached an image that can demonstrate it better than I can explain it. Thanks!

![jan 20 2015 21 52](https://cloud.githubusercontent.com/assets/5224/5831424/900a4248-a0ef-11e4-84dc-b9561dd85e74.gif)

**Comment by tonini** [comment]
Hi @robmerrell 

We're aware of this issue already.

Currently the indentation will be made after you hit `TAB` (`indent-for-tab-command`).

Thanks for reporting
