### ISSUE TITLE
Highlighting of built-in vs. user-defined modules

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/emacs-elixir#166]
[vim-elixir](https://github.com/elixir-lang/vim-elixir) highlights Elixir atoms (module names like `List` or `Plug.Conn`). emacs-elixir not highlighting them is the result of a design choice or of a kinda-bug?

Thanks in advance. I'd open a PR with an available solution (in case this is a bug) if only I had **any** experience with Emacs/elisp. I'm a total newbie :(

**Comment by tonini** [comment]
hey @whatyouhide 

Thanks for the report, I will have a look on it.

Cheers

**Comment by tonini** [comment]
@whatyouhide I had a look at it and in my case it's highlighting it well. But I think that has to do with the Emacs color theme you're using.

`elixir-mode` formats the module name with `font-lock-type-face`, maybe have a look at your theme which you're using and check what color it uses. 

![screenshot](http://i.imgur.com/eVCXGTl.png)

Regards

Samuel

**Comment by whatyouhide** [comment]
Hi @tonini,

this is what I get with the snippet of code you posted using solarized:

![screen shot 2015-01-24 at 13 01 04](https://cloud.githubusercontent.com/assets/3890250/5887312/186e3104-a3c9-11e4-979b-6065ccb6a229.png)

`Keyword`, `Enum` and so on are indeed highlighted correctly. However, this is what I get with a much shorter snippet (`Bar` should be highlighted as well):

![screen shot 2015-01-24 at 13 02 35](https://cloud.githubusercontent.com/assets/3890250/5887314/4ea5e0d2-a3c9-11e4-9e86-876ba468fc18.png)


(**PS** what colorscheme are you using? I could give it a try with that!)

**Comment by tonini** [comment]
I use https://github.com/tonini/emacs.d/blob/master/themes/ujelly-theme.el

You can easy change the color for modules as mentioned above for your color theme, just update the variable in the theme.

Cheers

**Comment by whatyouhide** [comment]
I installed and loaded the ujelly theme you linked, but the screenshot above doesn't change. Only Elixir stdlib modules are highlighted correctly:

![screen shot 2015-01-24 at 18 31 35](https://cloud.githubusercontent.com/assets/3890250/5888243/3efaf6a8-a3f7-11e4-81af-f4da092b4db0.png)

I don't know if this is the intended behaviour. As I mentioned in the issue, vim-elixir just highlights every capitalized word without knowing about Elixir stdlib modules. IMO, this is a much more consistent behaviour since stdlib modules are atoms just like modules defined by the user.

**Comment by mattdeboard** [comment]
Which names get highlighted is hard coded. The alternative approach would
be to highlight via regex

**Comment by whatyouhide** [comment]
@mattdeboard yes, which is what vim-elixir does and which is the behaviour I'd expect since capitalized words are almost always atoms in Elixir (except from the usual cases of capitalized words inside strings, charlists and similar cases).

**Comment by mattdeboard** [comment]
Indeed. Should be straightforward enough indeed to change.

**Comment by tonini** [comment]
@mattdeboard You're right, should I make a PR or would you like to do it?

**Comment by tonini** [comment]
@mattdeboard @whatyouhide so do you guys think we should just use the same font face like for `atoms`?

**Comment by whatyouhide** [comment]
@tonini I think vim-elixir gets it right here: no distinction between built-in modules and whatever capitalized atom (see the vim screenshot above).

**Comment by tonini** [comment]
@whatyouhide I like that, so it would be different from defining modules.

**Comment by whatyouhide** [comment]
> it would be different from defining modules

@tonini I'm not sure I understood you :( Anyways, what I mean is:

* regular atoms (like `:this` or `that:`) stay the way they're highlighted now
* "Elixir" atoms (meaning **any** capitalized word like `MyModule`, `Enum`, `Plug.Conn.Unfetched`) are highlighted as the same syntactic group (again, like the vim screenshot with `raise Foo.Bar` above).

If you meant that the highlighting of capitalized words should be different when they're used in the code as opposite to when they're used in, for example, `defmodule`, I think they shouldn't.

Capitalized words in Elixir are really just atoms with an alternative syntax, and `defmodule` and similar are just macros that take that atom as an argument. In my opinion, they should always be treated the same. Another vim screenshot for reference:

![screen shot 2015-01-25 at 10 21 34](https://cloud.githubusercontent.com/assets/3890250/5890997/ff2e5dfa-a47b-11e4-84b9-0f9ea97e4e4d.png)

(all capitalized words are the same)

**Comment by tonini** [comment]
@whatyouhide @mattdeboard 

For example:

![example](http://i.imgur.com/2wJ8giY.png)

So for defining `builtin-declaration` (`def`, `defmodule` etc) or `builtin-namespace` (`import`, `use` etc) it would use `font-lock-type-face` and for just used module name convention it uses a different font face, the same as for atoms `elixir-atom-face`.

what you guys think?

**Comment by whatyouhide** [comment]
@tonini I think highlighting `import`/`defmodule` differently than using modules (`Enum`, `Keyword` in the screenshot) is just confusing (again, this is since they're the same thing in the language).

**Comment by tonini** [comment]
Ok I see your point and thinks the way to go. I wi start with making the changes.

**Comment by whatyouhide** [comment]
@tonini great! Keep us updated :+1:

**Comment by tonini** [comment]
@mattdeboard what's the reason to use a fixed `elixir-atom-face` function for atoms?

Through that there is no way to customize the color look of atoms through the color-scheme itself.

Maybe we just could use the `font-lock-constant-face` for atoms?

What do you think about that?

**Comment by whatyouhide** [comment]
Hey there, any news on this? /cc @tonini @mattdeboard

**Comment by andreas-roehler** [comment]
On 11.02.2015 12:55, Andrea Leopardi wrote:
> Hey there, any news on this? /cc @tonini @mattdeboard
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/elixir-lang/emacs-elixir/issues/166#issuecomment-73870166
>

Hi,

case #167, https://github.com/elixir-lang/emacs-elixir/pull/171 is done,
volonteering for this, as it's expected pretty close an issue.

Andreas

**Comment by whatyouhide** [comment]
@andreas-roehler awesome! Keep us updated :)

**Comment by andreas-roehler** [comment]
On 11.02.2015 13:59, Andrea Leopardi wrote:
> @andreas-roehler awesome! Keep us updated :)
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/elixir-lang/emacs-elixir/issues/166#issuecomment-73876982
>


AFAIU that case deserves to be closed. Atoms are highlighted nicely with its own face.

Module-names --as discussed also-- IMO are a different matter anyway and should get its own ticket.
However, also nice AFAICS.

Cheers,

Andreas

**Comment by whatyouhide** [comment]
So any news/new opinions on this one? /cc @andreas-roehler @tonini

**Comment by andreas-roehler** [comment]
On 19.02.2015 16:36, Andrea Leopardi wrote:
> So any news/new opinions on this one? /cc @andreas-roehler @tonini
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/elixir-lang/emacs-elixir/issues/166#issuecomment-75072575
>

Suggest to merge as is.

Implementing a different face for string-interpolation should be possible, IMO a nice-to-have.
However looks like a non-trivial task and maybe not to most needed WRT known bugs.

**Comment by whatyouhide** [comment]
Anything on this? /cc @tonini @mattdeboard

**Comment by mattdeboard** [comment]
Not from me. :)

**Comment by whatyouhide** [comment]
@mattdeboard you think only stdlib modules should be highlighted but not
user-defined modules?

On Tuesday, March 17, 2015, Matt DeBoard <notifications@github.com> wrote:

> Not from me. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/emacs-elixir/issues/166#issuecomment-82617442>
> .
>


-- 

Andrea Leopardi
an.leopardi@gmail.com

**Comment by mattdeboard** [comment]
No, I don't think that at all. I think it's a worthy project to undertake, I just don't have the time for it at the moment.

**Comment by whatyouhide** [comment]
Ah okay, I didn't understand what your position was :).

I'm not fluent with elisp (and emacs is not even my main editor actually),
so I probably won't be able to tackle this. Not for a while at least :).

Let's hope @tonini or someone else will fix this!

On Wednesday, March 18, 2015, Matt DeBoard <notifications@github.com> wrote:

> No, I don't think that at all. I think it's a worthy project to undertake,
> I just don't have the time for it at the moment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/emacs-elixir/issues/166#issuecomment-82647168>
> .
>


-- 

Andrea Leopardi
an.leopardi@gmail.com

**Comment by mattdeboard** [comment]
Already the Atom editor's elixir "mode" seems much better equipped for languages with maximally significant whitespace.

**Comment by andreas-roehler** [comment]
On 18.03.2015 01:30, Matt DeBoard wrote:
> Already the Atom editor's elixir "mode" seems much better equipped for languages with maximally significant whitespace.
>

Hmm, what makes you thinking this?

BTW being not that current in elixir itself, got slightly confused by the labelling here.
An atom is syntactically defined in elixir, while a module name is a special thing.

So we talk here WRT module-names, elixir atoms as such are not at stake, right?

Cheers,

Andreas

**Comment by whatyouhide** [comment]
Elixir module names are atoms, but yes I'm specifically talking about
modules (not `:atoms` to be clear).

I think this is something like a regex for capitalized words away.

On Wednesday, March 18, 2015, Andreas Röhler <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> On 18.03.2015 01:30, Matt DeBoard wrote:
> > Already the Atom editor's elixir "mode" seems much better equipped for
> languages with maximally significant whitespace.
> >
>
> Hmm, what makes you thinking this?
>
> BTW being not that current in elixir itself, got slightly confused by the
> labelling here.
> An atom is syntactically defined in elixir, while a module name is a
> special thing.
>
> So we talk here WRT module-names, elixir atoms as such are not at stake,
> right?
>
> Cheers,
>
> Andreas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/emacs-elixir/issues/166#issuecomment-82925005>
> .
>


-- 

Andrea Leopardi
an.leopardi@gmail.com

**Comment by rranelli** [comment]
@mattdeboard I could try to work this out if everyone's okay with that.

**Comment by whatyouhide** [comment]
@rranelli please, do! :smile: :+1:

**Comment by andreas-roehler** [comment]
On 18.03.2015 14:32, Andrea Leopardi wrote:

> I think this is something like a regex for capitalized words away.
>

IMHO that was okay to start with - meanwhile we should implement it more reliable.
There might be other terms appear capitalized  too.

As a module name will show up at certain positions only, should be a way to determine that.

**Comment by whatyouhide** [comment]
I think capitalized words should not be highlighted only in a few (obvious) places: comments, strings, and `:`-prefixed atoms.

**Comment by rranelli** [comment]
I have created a pull request (#179) that addresses this Issue. It's still not mergeable because I want to add more test cases to the suite.

I have posed some questions there and would like to hear you guys opinions.

thanks

**Comment by andreas-roehler** [comment]
On 19.03.2015 03:40, Renan Ranelli wrote:
> I have created a pull request (#179) that addresses this Issue. It's still not mergeable because I want to add more test cases to the suite.
>
> I have posed some questions there and would like to hear you guys opinions.
>
> thanks

Hi Renan,

still an abstract reasoning:

IIUC there is no syntactic reason to capitalize a module name, it's just a convention, so a mode should not rely on this.
Even if regular expressions should be not powerful enough to determine a module name, Emacs will be able to solve that task: the fontifying machine optionally takes functions.

Cheers

**Comment by whatyouhide** [comment]
> there is no syntactic reason to capitalize a module name, it's just a convention

Wha do you mean @andreas-roehler?

**Comment by andreas-roehler** [comment]
On 19.03.2015 11:15, Andrea Leopardi wrote:
>> there is no syntactic reason to capitalize a module name, it's just a convention
>
> Wha do you mean @andreas-roehler?
>

IIUC elixir syntax accepts also lower-cased module-names.

**Comment by whatyouhide** [comment]
@andreas-roehler you can't define module names with lowecase atoms (at least not without prefixing them with `:`).

```elixir
defmodule foo do
end
#=> ** (RuntimeError) undefined function: foo/0
```

Capitalized words in Elixir are just a facility to represent atoms in the form `:"Elixir.Something":

```iex
iex> String == :"Elixir.String"
true
```

**Comment by andreas-roehler** [comment]
defmodule :foo do
  end

would work. While it's not capitalized.

**Comment by mattdeboard** [comment]
Ok here is my suggestion so we can bring this ticket to some kind of conclusion.

Ask one of the language contributors, probably in #elixir-lang on IRC, if it is safe to highlight all symbols that start with a capital letter as an atom. If it is then the fix should be fairly straightforward.
