### ISSUE TITLE
Highlighting issues inside triple-quoted strings

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/emacs-elixir#167]
Example from the Plug docs:

![screen shot 2015-01-24 at 20 01 56](https://cloud.githubusercontent.com/assets/3890250/5888559/1e30fe06-a404-11e4-9c68-df0719ce5f04.png)

I can reproduce it with just any triple-quoted string:

![screen shot 2015-01-24 at 20 04 12](https://cloud.githubusercontent.com/assets/3890250/5888562/2de7a9e4-a404-11e4-97bf-aa6833adc100.png)

This also leads to an incorrect behaviour when `"` strings inside triple-quoted strings don't have both the surrounding quotes. As always, we're better off with an example:

![screen shot 2015-01-24 at 20 06 01](https://cloud.githubusercontent.com/assets/3890250/5888566/71c08c58-a404-11e4-8a6f-0a9bd11f1d58.png)

IMO, stuff inside triple-quoted strings should be just highlighted as a string, whatever characters it contains. What do you think?

**Comment by tonini** [comment]
@whatyouhide Thanks for opening an issue for this one.

I think @mattdeboard has a much better knowledge about how `elixir-mode` handles `heredoc` representation. I know he has a lot to do, but maybe he could have a quick look into it. <3 :-)

**Comment by mattdeboard** [comment]
Triple-quoted strings are extremely difficult. I have tried many times to get this right. :(

The only thing I can suggest is to copy and paste python-mode's impl.

**Comment by whatyouhide** [comment]
I'd like to help *a lot*, but I really have not enough Emacs/elisp knowledge to to basically anything. It seems odd that triple-quoted-strings highlighting is so difficult. In vim (and vim-elixir), it's really simple to tell the editor to just highlight anything inside `"""` without breaking out of `"""`s (giving it precedence over single-quoted strings and so on).

**Comment by andreas-roehler** [comment]
On 24.01.2015 20:06, Andrea Leopardi wrote:

[ ... ]

While maintaining python-mode.el, whill have a look at it.

Cheers,

Andreas

**Comment by tonini** [comment]
Great! Thanks a lot :-)

Andreas Röhler <notifications@github.com> schrieb am Di., 3. Feb. 2015
13:36:

**Comment by andreas-roehler** [comment]
On 25.01.2015 19:08, Matt DeBoard wrote:
> Triple-quoted strings are extremely difficult. I have tried many times to get this right. :(
>
> The only thing I can suggest is to copy and paste python-mode's impl.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/elixir-lang/emacs-elixir/issues/167#issuecomment-71383872
>

Hi Matt,

having a look into your related branch, must have been pretty close to solution.
Sometimes its a kind of woodoo :)

Andreas,
your new contributor/collaborator

**Comment by mattdeboard** [comment]
The issue here is that triple-quoted strings (TQS) only get highlighted "correctly" by accident. A single TQS is, to the highlighting algorithm, 3 pairs of quotes. So the opening triple-quote is actually 1 full pair of quotes, and one half-pair of quotes, which is why the behavior described by @whatyouhide is happening. The highlighter sees the `"` before `application/json` as the closing quote to the last `"` in the opening triple-quote.

**Comment by andreas-roehler** [comment]
Seems that bug is fixed in trunk meanwhile, close?

**Comment by andreas-roehler** [comment]
Hmm, no, still there.

**Comment by mattdeboard** [comment]
Fixed by #203

**Comment by whatyouhide** [comment]
:heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: !!!
