### ISSUE TITLE
Error encountered when working with macros

### ISSUE THREAD

**Issue by edubkendo** [elixir-lang/emacs-elixir#168]
I've been working through the Metaprogramming Elixir book and have noticed that indentation seems to be rather problematic when defining macros.  Most of these I can work around ok, but since this one caused an actual error I thought I should report. I'm attaching a screenshot to illustrate:

![screenshot 2015-02-01 13 47 42](https://cloud.githubusercontent.com/assets/1395968/5993518/99bd0356-aa19-11e4-81c1-22e54cdb44a1.png)

As you can see, after hitting enter on the line with the comment, the cursor jerks all the way to the far left and an error shows up at the bottom. Thanks.

**Comment by tonini** [comment]
Thanks @edubkendo for reporting. 

I will have a look at it.

Cheers
