### ISSUE TITLE
unknown macro property "&define" in elixir-deftest

### ISSUE THREAD

**Issue by andreas-roehler** [elixir-lang/emacs-elixir#169]
When running tests from a shell-script, it breaks with error:
"unknown macro property &define in elixir-deftest"

See also

https://travis-ci.org/elixir-lang/emacs-elixir/jobs/46639534

Commenting out that lines at the end of file makes tests run.

Cheers,

Andreas

**Comment by tonini** [comment]
@andreas-roehler PR? :-)

**Comment by andreas-roehler** [comment]
Am 25.05.2015 um 15:48 schrieb Samuel Tonini:
>
> @andreas-roehler <https://github.com/andreas-roehler> PR? :-)
>
> —
>

Hmm, see this bug from my local run-travis.sh - could not spot the reason.

**Comment by andreas-roehler** [comment]
When running rake it tells:

Run test suite

Loading cl-indent...
Running tests on Emacs 24.3.1
Warning: Unknown macro property &define in elixir-deftest
.............................................................................

Ran 77 tests in 1.118 seconds
7 expected failures

**Comment by tonini** [comment]
@andreas-roehler We just can remove these additional line in the `declare` part of the `elixir-test` macro. There is no need to define them there. Ert get's the additional meta properties anyway.

3377e652e34644c789c6145b67cfe25ac0f1bacb

Thanks!
