### ISSUE TITLE
elixir-mode version > 2.1.0 breaks expand-region

### ISSUE THREAD

**Issue by jxs** [elixir-lang/emacs-elixir#174]
Hi there,
since updating 2.2.0 [expand-region](https://github.com/magnars/expand-region.el) breaks, there's no output on messages buffer, emacs just stops responding until i C-g 

thanks!

**Comment by rranelli** [comment]
I'm using the latest elixir-mode and could not reproduce the issue.

Have you tried updating your packages to their latest versions ? (are you using melpa ?)

Can you reproduce it by opening a clean emacs (emacs -q) and only requiring `elixir-mode` and `expand-region` ??

**Comment by jxs** [comment]
yes sorry for not giving better details, i am using expand region 0.10.0, all installed ia melpa
(had to downgrade to elixir-mode.el 2.1.0 after the issue)
i just launched emacs -q 24.4.1 on os x, then required manually expand-region and elixir-mode, and still have the same problem

**Comment by rranelli** [comment]
Hi @jxs,

It's nice that you managed to solve it. Just out of curiosity, what was the actual problem and how did you solved it ?

Thanks!

**Comment by jxs** [comment]
hi @rranelli, I am not sure what the actual problem was sorry, i think it was a conflict with another package version maybe, because i solved it by deleting my elpa packages folder and installing them all again

thanks
