### ISSUE TITLE
Wrong indentation after one line functions ending with a bitstring

### ISSUE THREAD

**Issue by larshesel** [elixir-lang/emacs-elixir#180]
```elixir
defmodule X do
  def a, do: <<1 :: size(8)>>
      def b, do: <<2 :: size(8)>>
          def c, do: <<3 :: size(8)>>
end
```

**Comment by mattdeboard** [comment]
So I tried adding a regression test for this but oddly enough, it passed, but it caused another test to fail.

```elisp
;; Will pass when #180 is resolved.
(elixir-def-indentation-test indent-after-bitstring/1
                             (:expected-result :failed :tags '(indentation))
"
defmodule X do
  def a, do: <<1 :: size(8)>>
      def b, do: <<2 :: size(8)>>
          def c, do: <<3 :: size(8)>>
end"
"
defmodule X do
  def a, do: <<1 :: size(8)>>
      def b, do: <<2 :: size(8)>>
          def c, do: <<3 :: size(8)>>
end")
```

This passed (unexpectedly), but had this for output:

```shell
Ran 70 tests in 0.276 seconds
7 expected failures
2 unexpected results:
   PASSED  elixir-ert-indent-after-bitstring/1
   FAILED  elixir-ert-indent-multiline-match
Test suite failed!
```

Obviously the latter test normally passes. How weird. There must be some kind of state mutation that we're not resetting after tests...

**Comment by tonini** [comment]
@mattdeboard @larshesel I suppose I found the issue.

Because of the bitstring in the `elixir-smie-backward-token` it's checking for `elixir-smie--binary-sequence-regexp` and returns `OP`.

So on line `3` below:

```elixir
   defmodule X do
     def b, do: <<1 :: size(8)>>
->   def b, do: <<2 :: size(8)>>
     def c, do: <<3 :: size(8)>>
   end
```

we get the following rules get called two times:

```
:before 'do:'; sibling-p:nil parent:((155) 18 def) prev-is-OP:nil hanging:nil == nil
:after 'OP'; sibling-p:nil parent:(114 25 do:) prev-is-OP:nil hanging:nil == (column . 2)
````

With the following changes to the `:after 'OP'` rule it would be fixed.

```lisp
(`(:after . "OP")
 (cond
  ((smie-rule-sibling-p) nil)
  ((smie-rule-hanging-p) (smie-rule-parent elixir-smie-indent-basic))
  ((and (not (smie-rule-sibling-p))
        (not (smie-rule-hanging-p))
        (smie-rule-parent-p "do:"))
   (smie-rule-parent -4))
  (t (smie-rule-parent))))
```

**Comment by tonini** [comment]
> Obviously the latter test normally passes. How weird. There must be some kind of state mutation that we're not resetting after tests...

@mattdeboard yeah we should have a look at this.

**Comment by larshesel** [comment]
@mattdeboard I just tested out the add-test-case-180 branch and the issue looks solved to me :+1:. haven't run the tests, though.
