### ISSUE TITLE
no indentation 

### ISSUE THREAD

**Issue by beadsland** [elixir-lang/emacs-elixir#181]
elixir-smie--semi-ends-match: Invalid function: (self-call nil (if (< (point) (point-max)) (elixir-smie--semi-ends-match) nil))

**Comment by mattdeboard** [comment]
Can you please provide more context so this can be triaged?

**Comment by andreas-roehler** [comment]
When reading the docu of the caller cl-flet:

Make local function definitions.
Like `cl-labels' but the definitions are not recursive.

wondering if the recursive call to elixir-smie--semi-ends-match is permitted then.
