### ISSUE TITLE
wrong indentation for multiclause anonymous functions

### ISSUE THREAD

**Issue by larshesel** [elixir-lang/emacs-elixir#184]
I would expect the clauses to be aligned vertically at the begin paren:

```elixir
defmodule X do
  def func do
    Enum.filter([1,2,3],
      fn(1) -> true
      (2) -> false
        (_) -> true
      end)
  end
end
```

**Comment by mattdeboard** [comment]
No, it is normal indentation when continuing a closure or function call on the following line.

**Comment by larshesel** [comment]
Hi @mattdeboard 
I'm not sure I understand completely - the second function clause '(2) -> false' has the same indentation as the first 'fn(1) -> true', but the third clause is indented two spaces. I'd expect the second clause to be indented as well or at least have all the clauses have no indentation, not a mix.

Doesn't the above look weird to you? Is there another way of writing the code so it looks better?

**Comment by larshesel** [comment]
If I extend the example a bit, I think it more clearly shows that the indentation of the different clauses is inconsistent:

```Elixir
defmodule X do
  def func do
    Enum.filter([1,2,3],
      fn(1) -> true
      (2) -> false
        (3) -> true
      (4) -> true
        (5) -> true
      (6) -> true
        (7) -> true
      (_) -> false
      end)
  end
end
```

**Comment by larshesel** [comment]
hey @mattdeboard - do you have time to take a look at my latest comments here? I really think there's an issue with the indentation here, although a minor one.

Cheers,
Lars

**Comment by andreas-roehler** [comment]
Indeed, seems definitely a bug

**Comment by larshesel** [comment]
Just pulled the branch: it seems to solve the issue and all tests passes (emacs 24.4.1)
