### ISSUE TITLE
`?"` confuses the syntax highlighter 

### ISSUE THREAD

**Issue by gausby** [elixir-lang/emacs-elixir#185]
Hi, thanks for a great package. I have a small problem and I think this is the right repo to report it in.

```elixir
"\"foo\"" |> String.strip(?")
```

Will confuse the syntax highlighter. Everything to the end of the file will be considered as a binary.

**Comment by andreas-roehler** [comment]
Am 19.05.2015 um 17:30 schrieb Martin Gausby:
>
> Hi, thanks for a great package. I have a small problem and I think 
> this is the right repo to report it in.
>
> "\"foo\""  |>  String.strip(?")
>
> Will confuse the syntax highlighter. Everything to the end of the file 
> will be considered as a binary.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elixir-lang/emacs-elixir/issues/185>.
>

The doublequote is special, needs to be quoted as a literal

"\"foo\""  |>  String.strip(?\")

**Comment by gausby** [comment]
Okay, that works. But I guess `?"` is valid Elixir, so I guess the highlighter should take it into account. (I wish I know more about elisp so I could give it a hurl myself)

**Comment by mattdeboard** [comment]
@gausby You are correct, it should work like this, and the fact that `?"` is not handled by the highlighter is a bug. However, if I recall correctly, as I was rewriting this mode last year this one specifically was quite difficult to fix. I agree it is annoying.

It can be very complicated. For example, how to tell the syntax highlighter to color 

```elixir
"""
"How should I color this?" she asked
"""
```

Also note that at least [one test](https://github.com/elixir-lang/emacs-elixir/blob/master/test/elixir-mode-font-test.el#L64-L70) deals with this issue. If you wanted to contribute, writing a test that captures your highlighting bug as an expected failure ([example](https://github.com/elixir-lang/emacs-elixir/blob/master/test/elixir-mode-font-test.el#L158)) would be a big help.

**Comment by mattdeboard** [comment]
By "if you wanted to contribute" I mean, "If you have the time and inclination to contribute". I think that could be misinterpreted as snark or something, but it definitely is not.

**Comment by gausby** [comment]
I do want to contribute; I was about to start an elixir emacs mode, but then Samuel started rocking hard on Alchemist, so I never got to start learning elisp because I could focus on Elixir (and my daytime job.)

I will look into adding the unit tests, but time are scarce, and I don't have a proper internet connection at home.

Do you know any good material on learning elisp; I know enough to do basic stuff in my emacs.d

**Comment by andreas-roehler** [comment]
Am 20.05.2015 um 07:31 schrieb Martin Gausby:
>
> I do want to contribute; I was about to start an elixir emacs mode, 
> but then Samuel started rocking hard on Alchemist, so I never got to 
> start learning elisp because I could focus on Elixir (and my daytime job.)
>
> I will look into adding the unit tests, but time are scarce, and I 
> don't have a proper internet connection at home.
>
> Do you know any good material on learning elisp; I know enough to do 
> basic stuff in my emacs.d
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elixir-lang/emacs-elixir/issues/185#issuecomment-103765599>.
>

Going through Elisp as provided by info was great for me.

**Comment by mattdeboard** [comment]
Good news and bad news.

Bad news is, this still isn't fixed.

The good news is, @andreas-roehler's TQS implementation does not get thrown off by `?"` tokens. That is, `?"` is highlighted normally in a triple-quoted string. This is good news because it means the solution, or *a* solution, can be adapted from his code for use in single-quoted strings.

**Comment by tonini** [comment]
Hey @syohex 

Do you think you could have a look at this issue if you get some time? 

Thanks

**Comment by tonini** [comment]
Fixed by https://github.com/elixir-lang/emacs-elixir/pull/340
