### ISSUE TITLE
config.exs indentation issue

### ISSUE THREAD

**Issue by larshesel** [elixir-lang/emacs-elixir#194]
When working with config/config.exs and similar files, the indentation of the generated files does not macht the behaviour of emacs-elixir.

Emacs-elixir wants to indent like this (no indentation):

```Elixir
use Mix.Config

config :hello_phoenix, HelloPhoenix.Endpoint,
url: [host: "localhost"],
root: Path.dirname(__DIR__)
```

But the existing indentation looks like this:
```Elixir
use Mix.Config

config :hello_phoenix, HelloPhoenix.Endpoint,
  url: [host: "localhost"],
  root: Path.dirname(__DIR__)
```

**Comment by mattdeboard** [comment]
Yeah that sort of alignment won't be supported anytime soon or ever, most likely. Left-aligned is the likeliest future.
