### ISSUE TITLE
Indentation of functions that use :do instead of do...end

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/emacs-elixir#201]
Indentation of functions that use the `:do` syntax (`, do: ...`) instead of the `do ... end` syntax is brokenish. In the example below, the `*` character represents the cursor position.

### Example on a single line

**EDIT**: fixed by the awesome @tonini!

### Example on multiple lines

```elixir
def a,
do: :b # this should be indented someway, I recommend 2 spaces as it's the convention in elixir stdlib
```

Btw, I think the same should happen with this pattern, also very common in the stdlib:

```elixir
def a
  when foo,
  do: :b
```

which is instead indented as:

```elixir
def a
when foo,
do: :b
```

**NOTE** all of the above examples behave the same if the defined function has arguments, as well as with `def`/`defp`/`defmacro`/`defmacrop`.

**Comment by mattdeboard** [comment]
Fixed by #202
