### ISSUE TITLE
Fontify string-interpolation

### ISSUE THREAD

**Issue by andreas-roehler** [elixir-lang/emacs-elixir#206]
As expected: due to fixes of #167, fontify triple-quoted-string, string-interpolation lost its face

**Comment by andreas-roehler** [comment]
syntax-propertize-rules don't allow overlapping matches - first match takes all.
Maybe find a solution for TQS which doesn't employ this - see old python.el resp. python-mode.el

**Comment by andreas-roehler** [comment]
A solution should be possible along this:

http://emacs.stackexchange.com/questions/13128/highlighting-shell-variables-within-quotes

**Comment by rranelli** [comment]
Could this issue be closed ?

**Comment by mattdeboard** [comment]
Fixed by #269
