### ISSUE TITLE
Binary syntax (<<>>) throws number highlighting off

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/emacs-elixir#207]
`elixir-mode` highlights numbers (which is great), but the binary syntax `<<>>` throws the highlighting off. Minimal example to reproduce:

```elixir
<<1, 2, 3>>
```

the example looks like this:

![screen shot 2015-05-27 at 09 32 07](https://cloud.githubusercontent.com/assets/3890250/7831074/727acee2-0453-11e5-960c-1bbe85e834d0.png)

where the first number isn't highlighted (I guess due to being next to `<<`) and the trailing `>>` is highlighted.

**Comment by mattdeboard** [comment]
Is there even value in highlighting numbers separately?

**Comment by whatyouhide** [comment]
Well, personally I like highlighted numbers a lot but I was just reporting the bug in this case :)

**Comment by tonini** [comment]
I asking myself the same like @mattdeboard mentioned. Should we really highlighting numbers separately? 

I would like to fix that and remove highlighting from numbers at all.

#208

**Comment by whatyouhide** [comment]
AS I mentioned in #208, this was probably a problem related with some other mode (like [this](https://github.com/Fanael/highlight-numbers)) which highlighted numbers by itself. I don't think elixir-mode highlights numbers at all.

That said, while I like number highlighting a lot, I realise it adds complexity to elixir-mode for very little gain so I'm :+1: on not highlighting them. You can remove any related code (if there's any, at this point I don't think there is).
