### ISSUE TITLE
Negative numbers are highlighted differently than positive numbers

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/emacs-elixir#208]
Well actually they aren't highlighted at all:

![screen shot 2015-05-27 at 09 38 37](https://cloud.githubusercontent.com/assets/3890250/7831156/2bab3dc0-0454-11e5-8e57-8a7fda6b0023.png)

**Comment by tonini** [comment]
I don't get any highlighting at all for numbers. (pos/neg)

Hm, do you get this with the current master?

**Comment by whatyouhide** [comment]
@tonini actually I'm trying this now and I don't get any highlighting for numbers either. Given that I was using [spacemacs](https://github.com/syl20bnr/spacemacs) at the time I reported this bug, it may be that something like [this](https://github.com/Fanael/highlight-numbers) was enabled and I didn't know that.

We can close this and continue to discuss if highlighting number is worth it in #207.
