### ISSUE TITLE
Shorter prefix

### ISSUE THREAD

**Issue by andreas-roehler** [elixir-lang/emacs-elixir#209]
IMO reading source-code will be easier with a shorter prefix, so reader might focus on the part which matters.

With "elixir-mode-bla-blub" the "-mode-" part is redundant.

Also "elixir-" might be shorter, as not keeping info by themself. What about "exs-"?

**Comment by mattdeboard** [comment]
This seems like an unnecessary change. What problem does it solve?

**Comment by andreas-roehler** [comment]
Seems we agreed onto "elixir-" meanwhile. Shorten "elixir-mode-fill-doc-string" onto "elixir-fill-doc-string" etc. should be a progress.
