### ISSUE TITLE
  // , Can emacs-elixir be used in conjunction with Emacs Evil-mode? 

### ISSUE THREAD

**Issue by v6** [elixir-lang/emacs-elixir#216]
// , I use Evil-mode with Programmer Dvorak.

**Comment by tonini** [comment]
emacs-elixir is just a language [major mode](http://www.gnu.org/software/emacs/manual/html_node/emacs/Major-Modes.html) so you just can use it like any other major or minor mode with Evil-Mode.

**Comment by v6** [comment]
// , Good. Thanks for saving me the time I'd have spent testing it out.
