### ISSUE TITLE
Atoms highlighted incorrectly in pattern matches

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/emacs-elixir#218]
When an atom is used as the only thing on the left-hand side of a pattern match, it's highlighted incorrectly (meaning not as an atom, but like when there's a single variable on the LHS):

![screen shot 2015-06-15 at 16 04 24](https://cloud.githubusercontent.com/assets/3890250/8161555/3940758a-1378-11e5-92d7-0741f2cc0ca5.png)

**Comment by tonini** [comment]
As always, thanks for reporting :+1:
