### ISSUE TITLE
Module name isn't highlighted in some cases

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/emacs-elixir#224]
Module names aren't highlighted if preceded by a pipe `|` character. This is the minimal example to reproduce the behaviour:

    |List

and this is a screenshot of the behaviour in action:

![screen shot 2015-06-20 at 18 28 36](https://cloud.githubusercontent.com/assets/3890250/8293698/8fa412b4-1937-11e5-89c1-819dd5108b53.png)

**Comment by michalmuskala** [comment]
It also doesn't work correctly with `&`
![screenshot from 2015-07-14 10 30 14](https://cloud.githubusercontent.com/assets/477062/8669278/7de7beee-2a13-11e5-958d-f59c65d9db8c.png)

**Comment by tonini** [comment]
Thanks for reporting

**Comment by tonini** [comment]
#233

**Comment by tonini** [comment]
@syohex I guess you have a solution for this one? ;-)

**Comment by syohex** [comment]
I suppose `elixir-mode` should change syntax of such characters from symbol character to punctuation character as following patch.  Any other characters than `&`, `|` ?

```diff
diff --git a/elixir-mode.el b/elixir-mode.el
index 77a0f6b..d4c0a3c 100644
--- a/elixir-mode.el
+++ b/elixir-mode.el
@@ -496,6 +496,10 @@ just return nil."
        #'elixir-syntax-propertize-function)
   (set (make-local-variable 'imenu-generic-expression)
        elixir-imenu-generic-expression)
+
+  (modify-syntax-entry ?| "." elixir-mode-syntax-table)
+  (modify-syntax-entry ?& "." elixir-mode-syntax-table)
+
   (smie-setup elixir-smie-grammar 'verbose-elixir-smie-rules
               :forward-token 'elixir-smie-forward-token
               :backward-token 'elixir-smie-backward-token))
```

Sreenshot with above patch is here.

![fixed](https://cloud.githubusercontent.com/assets/554281/10581202/6cf99d64-76bc-11e5-88f4-481db986a3fb.png)

**Comment by tonini** [comment]
That sounds like a good idea, would you like to make a PR?

Syohei YOSHIDA <notifications@github.com> schrieb am Mo., 19. Okt. 2015
16:53:

**Comment by syohex** [comment]
:+1:

**Comment by tonini** [comment]
Thanks again for your help :+1:
