### ISSUE TITLE
Double quote characters within a regex

### ISSUE THREAD

**Issue by duff** [elixir-lang/emacs-elixir#226]
When the `"` character appears in a Regex, the highlighting is attempting to treat it as a binary rather than just another character in the Regex.  So, for example, if I have a Regex such as:

```
    regex = ~r/<a href="([^"]*)"/
    # Some comment
    i = index
```

the highlighting looks like this:

![line_ex](https://cloud.githubusercontent.com/assets/2437/8498262/ac753c4c-2152-11e5-963d-1d5a96a0c4c3.jpg)

So it looks like it's thinking that part of the Regex is a string.  And then, since there are an odd number of `"` characters in the Regex, the remainder of the file's highlighting is off since it's waiting to have the `"` closed.

I haven't yet been able to determine how to actually fix it. :)  I see there are a number of lines handling sigils and a number of lines handling regexes.  I thought I'd report things here in case anyone might have ideas as I research more.

**Comment by michalmuskala** [comment]
Related - the highliting is also broken for char `?"`
![screenshot from 2015-07-14 10 24 09](https://cloud.githubusercontent.com/assets/477062/8669202/da7fcd1e-2a12-11e5-95e6-cbae7ffe584c.png)

**Comment by gausby** [comment]
@michalmuskala #185 has some discussion about `?"`

**Comment by michalmuskala** [comment]
Thanks, I must have missed it.
