### ISSUE TITLE
Indentation of parameters when no parenthesis are used

### ISSUE THREAD

**Issue by manukall** [elixir-lang/emacs-elixir#229]
```elixir
defmodule MyMailer do
  use Mailgun.Client, domain: Application.get_env(:my_app, :mailgun_domain),
  key: Application.get_env(:my_app, :mailgun_key)
end
```

should the line starting with `key: ...` be indented one more level? the same happens in config files generated by phoenix.

**Comment by whatyouhide** [comment]
:+1: yes I think it should.

**Comment by tonini** [comment]
This is really hard to accomplish because of Elixir's flexible syntax.

> should the line starting with key: ... be indented one more level? the same happens in config files generated by phoenix.

How uniq is this case? I mean are there any other situations where a key (`whatever:`) would be at the beginning of a line?

**Comment by manukall** [comment]
i don't think it's that uniq. the automatically generated config files from phoenix are full of that. the example above is also copied from the mailgun readme.

could checking whether the line before ended with a "," work?

**Comment by tonini** [comment]
I need to test some cases for that. :)

Thanks for the reporting, I'll have a look at it and report back if I get something to work with.

**Comment by manukall** [comment]
cool. let me know if i can help.

**Comment by tonini** [comment]
I got the whole thing working on a local branch and will push as soon as possible. 

![](http://i.imgur.com/Y9UFGF9.gif)

/cc @gausby

**Comment by whatyouhide** [comment]
This is absolutely glorious :muscle:

**Comment by gausby** [comment]
I don't know if it is the wine from the Goto-conference-launch-party that is speaking, but I freaking love this!

**Comment by tonini** [comment]
fixed by https://github.com/elixir-lang/emacs-elixir/commit/f721fb45e6860073c93840e502b9c6a56db42ab2

**Comment by manukall** [comment]
:heart_eyes: works great. thanks!
