### ISSUE TITLE
Emacs hangs when point moved to a one-line function definition

### ISSUE THREAD

**Issue by jimm** [elixir-lang/emacs-elixir#239]
Save the following two lines as an .ex or .exs file and open it in Emacs. Move to the second line. Emacs hangs. My CPU meter shows it's using 100% CPU.

```elixir
def two_digit_str(num) when num < 10, do: "0#{num}"
def two_digit_str(num), do: "#{num}"
```
I'm using Emacs for Mac OSX (http://emacsformacosx.com/) and running the latest Mac OS X version, 10.10.5. The Elixir package I'm using is 20150807.338 from MELPA.

**Comment by gausby** [comment]
Confirmed.

You should notice that you cannot create named functions outside of modules in Elixir/Erlang. But it does feel like there is some slight lag (a tiny amount) when moving the cursor over the definitions when they are put into a module as well.

**Comment by jimm** [comment]
Thanks for the quick response! I was originally writing a .exs file, and thought that I didn't have to have everything inside a module, but that makes perfect sense. When I put those two lines inside a module, I don't feel much of a delay on my system. I'm guessing the delay is SMIE, but am not familiar enough with it to have any suggestions.

**Comment by tonini** [comment]
Hi @jimm and @gausby 

Thanks for reporting this issue. I'm already on it :+1:

**Comment by jimm** [comment]
@tonini thank YOU.

**Comment by jimm** [comment]
Oops. Ignore the close/reopen. Sorry.

@tonini Thanks for looking into this. I'd love to learn how to debug this kind of thing. Adding `message` print statements to the code?

**Comment by tonini** [comment]
@jimm I'm using `edebug` https://www.gnu.org/software/emacs/manual/html_node/eintr/edebug.html

But in this case it's actually hard because Emacs hang up. :-) I will have a look at it soon I get some free time.

Thanks

**Comment by mattdeboard** [comment]
If it were me I'd probably look at the grammar which definitely seems incomplete. Like [here](https://github.com/elixir-lang/emacs-elixir/blob/master/elixir-smie.el#L116) is the only line where `do:` is mentioned as a token. Of course historically I would spend hours tinkering with the grammar only to give up in the end and just add another rule to `elixir-smie-rules` to special-case it.

I'll butt out!

**Comment by jimm** [comment]
Thank you!

**Comment by tonini** [comment]
You're welcome! Thanks for reporting :+1:
