### ISSUE TITLE
Correct indentation for pipe operator

### ISSUE THREAD

**Issue by hunterboerner** [elixir-lang/emacs-elixir#243]
The [elixir style guide](https://github.com/niftyn8/elixir_style_guide) recommends this:

```elixir
# Multiline pipelines use a single level of indentation.
some_string
|> String.downcase
|> String.strip

# Multiline pipelines on the right side of a pattern match
# should be indented on a newline
sanitized_string =
  some_string
  |> String.downcase
  |> String.strip
```

emacs-elixir will indent the second example as:

```elixir
sanitized_string =
  some_string
|> String.downcase
|> String.strip
```

It would be nice if support for the elixir style guide format could be added. Thanks :)

**Comment by gausby** [comment]
Also, I have seen core code written like this:
```elixir
some_thing = some_string
             |> String.downcase
             |> String.strip
```
I don't know what the Elixir community think of that style, but I kinda like it.

**Comment by whatyouhide** [comment]
Hey @gausby, yes there definitely is code like the one you showed in the Elixir core. However, have a look at [this discussion](https://github.com/niftyn8/elixir_style_guide/pull/33), the consensus is pretty much set on @hunterboerner's example.

PS, :+1: on the issue!

**Comment by gausby** [comment]
@whatyouhide coming from a node.js background I can say that it is really easy to change ones preferences when it comes to formatting, so I can change...but coming from a node.js background I also have some scepticism when it comes to style-guides…in this case I don't really buy the argument about the eyes that has to travel a further distance; seems more like a statement of personal aesthetics than something that is backed by studies.

But I can adapt to the equals-new-line-pipe-style. :)
