### ISSUE TITLE
true, false and nil also higlighted inside other identifiers

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/emacs-elixir#245]
We recently gained highlighting for `true`, `false` and `nil` as atoms. But they are also highlighed when appearing inside function or variable names. 

For example:
![screenshot from 2015-09-05 19 36 28](https://cloud.githubusercontent.com/assets/477062/9700502/883341ea-5405-11e5-9f71-7b0a86c7b498.png)

**Comment by syohex** [comment]
I sent PR #246 for this issue.

**Comment by tonini** [comment]
fixed with #246
