### ISSUE TITLE
error "Variable binding depth exceeds max-specpdl-size"

### ISSUE THREAD

**Issue by beedub** [elixir-lang/emacs-elixir#254]
I'm getting the error above when pressing on the last line in the code below. Any ideas?

```elixir
case parse do
  {} -> :hello
```

**Comment by gausby** [comment]
The `Error: (error "Lisp nesting exceeds `max-lisp-eval-depth'")` error will go away if the do block is ended like this:
```elixir
case parse do
  {} -> :hello
end
```
Omitting the `end` will cause a parse error.

**Comment by tonini** [comment]
:+1: Let me check that. :smile:
