### ISSUE TITLE
Improper indentation for underscore in case

### ISSUE THREAD

**Issue by beedub** [elixir-lang/emacs-elixir#255]
It indents properly with one preceding clause, but when there are two or more preceding clauses, it indents one too many.

Not sure if this is related to https://github.com/elixir-lang/emacs-elixir/issues/254

```elixir
case parse do
  {} -> :help
  {}
    -> :help
    _
    -> :help
```

**Comment by tonini** [comment]
:+1: Thanks! I'll have a look at this one too. :smile:

**Comment by gausby** [comment]
I haven't seen this form of indentation in the wild. I think the arrow should be on the same line as the match like so:
```elixir
case parse do
  {} -> :help
  {} ->
    :help
end
```
These indentations are supported by the currently, and are in my opinion the most readable.

**Comment by whatyouhide** [comment]
```elixir
x
  -> :foo
```

is something I never witnessed in any of the Elixir projects I worked on. I'm personally strongly 👎 on introducing another style for this, and hence I think we shouldn't bother supporting this in `elixir-mode` :)

**Comment by gausby** [comment]
Let me elaborate on my previous statement about being «more readable». I would probably question the intent if a saw a hanging arrow like that. Does the line belong to the block above, or is it the actual match?

That train of thought is eliminated if the match is on the same line as the arrow. I think this is a case that should be grabbed by tools like Credo, if it doesn't already.

**Comment by tonini** [comment]
I agree with the opinions of @gausby and @whatyouhide 

Thanks @beedub for the feedback.

I'll close this issue for now.

**Comment by beedub** [comment]
The example I had in the original is actually misleading. I haven't scripted in elixir in a bit, but here's what I think I meant (and just tested):

```elixir
case parse do
  {} -> :help
  {} -> :help
    _
```

Tabbing on the final line with an underscore leaves it indented it even though it shouldn't be indented (right?). However, adding the `->` after the `_` fixes the indentation:

```elixir
case parse do
  {} -> :help
  {} -> :help
  _ ->
```

This behavior seems to be specific to `_` as `{}` is properly indented even without a trailing `->`:

```elixir
case parse do
  {} -> :help
  {} -> :help
  {}
```

Tabbing on the last line above keeps it at the proper indent

**Comment by tonini** [comment]
hey @beedub 

Thanks for the detailed explanation.
It's fixed on master now, you just need to wait until melpa.org build the latest emacs-elixir package from master.

**Comment by whatyouhide** [comment]
I think clauses without `->` should be indented one level more than clauses with `->` in them.

```elixir
case start_link() do
  {:ok, pid} -> pid
  {:error, reason} -> IO.inspect(reason)
    :error
end
```

is valid Elixir and the `{:error, reason}` clause will execute both `IO.inspect(reason)` as well as return `:error`; i.e., the code above is equivalent to:

```elixir
case start_link() do
  {:ok, pid} -> pid
  {:error, reason} ->
    IO.inspect(reason)
    :error
end
```
