### ISSUE TITLE
Comprehension (mis)indentation

### ISSUE THREAD

**Issue by beedub** [elixir-lang/emacs-elixir#256]
Returning on a one-line comprehension shouldn't indent the next line, right?

```elixir
blah = for i <- list, do: i
  # this line should not be indented
```

**Comment by gausby** [comment]
Hi, this doesn't seem to be a problem in master. I think that you might be running an older version.
```elixir
blah = for i <- list, do: i
# this line should not be indented
```

**Comment by beedub** [comment]
Ah, looks like I removed necessary dependent code from the test case. Adding `defmodule` before it makes the indentation weird.

```elixir
defmodule Hello do
end

hi = for i <- list, do: i
  # weird spacking now
```

**Comment by tonini** [comment]
Thanks! I'll have a look at this too. :smile:
