### ISSUE TITLE
doublequote in sigil string confuses highlighter

### ISSUE THREAD

**Issue by alxndr** [elixir-lang/emacs-elixir#265]
A string defined with a sigil containing a lone doublequote (i.e. `~s(")`) will confuse the syntax highlighter:

![screen shot 2015-10-08 at 14 51 45](https://cloud.githubusercontent.com/assets/174307/10381019/7aeb8c50-6dcc-11e5-8080-a44903ad7adf.png)

**Comment by tonini** [comment]
@alxndr this one is already reported with #185

Thanks :+1:
