### ISSUE TITLE
Correct anonymous fun indentation inside `case` and `cond`

### ISSUE THREAD

**Issue by lexmag** [elixir-lang/emacs-elixir#274]
The anonymous fun arrow `->` breaks an indentation.

<img width="217" alt="screen shot 2015-10-21 at 21 47 10" src="https://cloud.githubusercontent.com/assets/248290/10648314/ed2c693a-783d-11e5-9f3b-9b2b5a213b86.png">

**Comment by tonini** [comment]
Thanks for the report @lexmag

**Comment by unbalancedparentheses** [comment]
I am having the same issue. The arrow breaks the indention.
