### ISSUE TITLE
Erlang string formatting directive confuses syntax highlighter

### ISSUE THREAD

**Issue by ianrumford** [elixir-lang/emacs-elixir#275]
Hi all,

As usual, want to express my thanks for this awesome major mode.

Bumped up to 2.2.8 a couple of days ago and saw this effect in a file containing an Erlang string formatting directive e.g.

```elixir
@one 1
@two "~s"
@tre :tre
```

Github doesn't show the "broken" colour: the third line is all red, and, in my file, the rest of the code is red, with comments green.

If you delete the tilde, the effect goes away.  Same effect with "~w" as well.

**Comment by syohex** [comment]
@ianrumford #277 has been merged. Please check latest version.

**Comment by tonini** [comment]
@ianrumford maybe you need to wait until MELPA built the latest elixir-mode
package ftom master

Syohei YOSHIDA <notifications@github.com> schrieb am Fr., 23. Okt. 2015
07:46:

**Comment by ianrumford** [comment]
Thanks guys.  I'll take Tonini's advice and wait for the next version on MELPA
