### ISSUE TITLE
Correct indentation for sucessive macro calls

### ISSUE THREAD

**Issue by ianrumford** [elixir-lang/emacs-elixir#281]
Hi all,

Props as always to you guys.

Just seen this on v2.2.8

I have (many) successive calls to one of my macros and the indentation steps to the right for each call and never recovers, even after the last macro call.

For example:

```elixir
mymacro x1, do: [:x1]
  mymacro x2, do: [:x2]
    mymacro x3, do: [:x3]
```

**Comment by tonini** [comment]
@ianrumford Thanks for the report.

The issue is fixed on master now (https://github.com/elixir-lang/emacs-elixir/pull/282).

You need to wait until MELPA has build the new package and then just `list-packages` and update `elixir-mode`

Thanks

**Comment by ianrumford** [comment]
Obliged. later.
