### ISSUE TITLE
Syntax highlighter does not highlight `end` when the last line in a module is a comment

### ISSUE THREAD

**Issue by gausby** [elixir-lang/emacs-elixir#283]
Not the most important issue in the world, but I've noticed an issue that might be a bit hard to describe in text; I'll try anyway.

If a module has a comment on the last line the `end` will stop getting highlighted until the line with `end` has been updated. If we update the line with the comment the line with `end` will stop highlighting again.

Again, this is not critical. It is just a minor thing I've noticed happens that should not happen. I'll post a unit test shortly.

**Comment by tonini** [comment]
Fixed on master.

Thanks @gausby :yellow_heart:
