### ISSUE TITLE
Syntax highlighting gets destroyed with ~S""" heredoc prefix

### ISSUE THREAD

**Issue by tonini** [elixir-lang/emacs-elixir#286]
When an `heredoc` as an `sigil` in front of it, the whole syntax highlighting gets messed up.

Example source: https://github.com/elixir-lang/elixir/blob/master/lib/iex/lib/iex.ex#L2

@syohex do you have an idea how to handle this? :-)

![Example](http://i.imgur.com/WASghDA.png)

**Comment by syohex** [comment]
Could you check #287 patch ?

**Comment by tonini** [comment]
:+1:
