### ISSUE TITLE
Indentation of non-finished one-line if-else

### ISSUE THREAD

**Issue by gausby** [elixir-lang/emacs-elixir#290]
Considering how we should indent non-finished one-line-def example:
```elixir
def name,
  do: :foo
```
I think it would make sense if single-line-if-else indenting with the following behaviour:
```elixir
# current
if condition,
do: :foo,
else: :bar

# expected
if condition,
  do: :foo,
  else: :bar
```
Am I correct in thinking so, or should splitting a one-line conditional like this result in the current behaviour?

I will provide a unit test for the expected behaviour in my example.

**Comment by tonini** [comment]
Yes I think that would be correct.

**Comment by mattdeboard** [comment]
Whatever format we decide on for this, I think it should be consistent with the solution in #294 as well as the new `with` syntax announced in the [Elixir 1.2 release notes](https://github.com/elixir-lang/elixir/releases/tag/v1.2.0).

**Comment by lexmag** [comment]
Speaking about `with`, there is expected indentation for it: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel/special_forms.ex#L1372.
