### ISSUE TITLE
Font lock features

### ISSUE THREAD

**Issue by hunterboerner** [elixir-lang/emacs-elixir#292]
I noticed two things in Elixir Sips that would be nice in emacs-elixir: quote identifiers being a different color and variables starting with `_` being grayed out. Screenshots of what I'm talking about below:

![screenshot 2015-11-07 14 14 21](https://cloud.githubusercontent.com/assets/1314119/11017087/01f3cbf0-855a-11e5-97df-85902211d835.png)
![screenshot 2015-11-07 14 14 13](https://cloud.githubusercontent.com/assets/1314119/11017088/038a923c-855a-11e5-9bb0-d0b7720dfeb1.png)

Any chance these could be added?

**Comment by whatyouhide** [comment]
I'd love for `_variables` to be greyed out, especially because we have `_` highlighted differently in emacs-elixir. To me, `_` and `_variable` have the same meaning (even if there are a couple of semantic differences in how Elixir treats them).

**Comment by hunterboerner** [comment]
@tonini what about the quote styling?

**Comment by mattdeboard** [comment]
Marking as `wontfix` and closing. If you would like to submit a patch for the fontified quote delimiters that works in every case, we will review that. Thanks
