### ISSUE TITLE
~2 second delay when pressing <return> after a "do"

### ISSUE THREAD

**Issue by rcoedo** [elixir-lang/emacs-elixir#293]
I'm having issues with elixir-mode, not sure what is causing this.

When writing a function definition, after typing the do and pressing return, emacs just hangs for a couple of seconds. It happens with function definitions only (module definitions seem to work well).

eg. "def xxx do<return>" or "defp xxx do<return>" has delay. "defmodule XXX do<return>" has no delay.

I tried a clean emacs install with only the elixir-mode package and it happens too. I'm using emacs 24.5.1.

**Comment by mattdeboard** [comment]
This is interesting. Can you paste your sample code where you're seeing this? It'd be interesting to bisect back and see where this delay was intro'd.

**Comment by rcoedo** [comment]
An empty file with just "def xxx do" will do it. Let me know if you need more details.

**Comment by syohex** [comment]
Could you check with following configuration ?

```lisp
(setq blink-matching-paren nil)
```

**Comment by rcoedo** [comment]
That worked @syohex!

**Comment by syohex** [comment]
Or set small value to `blink-matching-delay`. Default of `blink-matching-delay` is 1 and emacs sleeps its delay before inserting newline.

```lisp
(setq blink-matching-delay 0.1)
```

**Comment by rcoedo** [comment]
Thanks again @syohex. I'll close the issue since it had nothing to do with elixir-mode after all :)
