### ISSUE TITLE
Wrong indention for multiline defstruct

### ISSUE THREAD

**Issue by mmainz** [elixir-lang/emacs-elixir#294]
When I use `defstruct` where the arguments span multiple lines, it does not indent the following lines.

![image](https://cloud.githubusercontent.com/assets/5417714/11341657/aea0c622-9203-11e5-999c-9f346066bf57.png)

When I use parentheses, it works as intended.

![image](https://cloud.githubusercontent.com/assets/5417714/11341670/c16f08f4-9203-11e5-9c16-64e01d5c2e00.png)

I noticed you don't have any tests including a `defstruct`, so I quickly wrote one to demonstrate the behavior. Hope I did that right! You can look at it here: https://github.com/elixir-lang/emacs-elixir/commit/b5abe3abf041cca9ea4bb0337bb47dd5b385e9ed

**Comment by gausby** [comment]
I guess this is a question about coding conventions and style, but multiline `defstruct`s created with parenthesis works fine:
```elixir
defmodule User do
  defstruct(
    first_name: "Mario",
    last_name: "Mainz"
  )
end
```
I think this is they direction every styleguide seems to go.

But, you can create a pull request with your unit test and have it accepted if you add the `:expected-result :failed` argument to the test; an example on how to do this is in the test just beneath yours. That way a maintainer can toggle this flag and start work on the indentation.

I hope this helps.

**Comment by mmainz** [comment]
I created a pull request. I'd be happy to implement this myself, but I never worked on anything that has to do with code syntax, so I'm not sure whether I will understand the necessary parts.

**Comment by whatyouhide** [comment]
@gausby I'm not sure about style guides, but the vast majority of Elixir code I read (and write for that matter) uses the convention @mmainz is using for struct definitions:

```elixir
defstruct foo: 1,
               bar: 2,
               baz: 3
```

Just to join the conversation :smile: and cause I'd love this in emacs-elixir actually :\

**Comment by gausby** [comment]
@whatyouhide I could be mistaken, but I think that I remember some talk on the core mailing list discussing the upcoming with-syntax that would require indentation like the one I suggested (and are fairly sure I haven't made it up)

Again, I could be mistaken. I just don't want someone to put time into some indentation rules that would end up not getting accepted.

**Comment by tonini** [comment]
Currently the indentation for the `defstruct` example is the same as for every other function call. So If we come up with a proper convention/solution many other cases should then be correct/fixed.

**Comment by mattdeboard** [comment]
>  some talk on the core mailing list discussing the upcoming with-syntax that would require indentation like the one I suggested

@gausby is right. With the 1.2 release, there is indeed a `with` syntax that requires formatting like:

```
keyword expr,
        expr
```

**Comment by mattdeboard** [comment]
This appears to be a special case of #229
