### ISSUE TITLE
Wrong indentation of the last key in a multiline maps on the match side within case statements

### ISSUE THREAD

**Issue by gausby** [elixir-lang/emacs-elixir#297]
Wrong indentation of the last key in a multiline maps on the match side within case statements.

Current:
```elixir
case statement do
  %{"foo" => "foo",
     "baz" => "baz"} ->
    :ok

  _ ->
    :ok
end
```

Expected.
```elixir
case statement do
  %{"foo" => "foo",
    "baz" => "baz"} ->
    :ok

  _ ->
    :ok
end
```

Notice the extra space before the "baz" key in the current example.

I would mark this issue as low priority, but it is better to report it :)

A pull request with a unit test is coming up

**Comment by mattdeboard** [comment]
This is _also_ a specific case of #229, since `do` is a function.
