### ISSUE TITLE
Markdown support in docs

### ISSUE THREAD

**Issue by cjhowe** [elixir-lang/emacs-elixir#300]
Can we add something like [mmm-mode](https://github.com/purcell/mmm-mode) for using `markdown-mode` within docs? Ideally code examples inside those docs can also switch back to `elixir-mode`. This would make indentation inside docs a lot simpler, and also improve the user experience for writing documentation. Anything to make writing docs and doctests more enjoyable!

Here's an example:

    module DocExample do
      # starts in elixir-mode
      @moduledoc ~S"""
      Then, we go to `markdown-mode` in docs.
      ## Example
          # Now, we are in elixir-mode
          IO.puts "hello, world"
      Back to `markdown-mode`.
      """
      # finally, we go back to elixir-mode
    end

**Comment by gausby** [comment]
I agree that this would be neat, and I have been thinking about it to my own emacs config myself, but this should* not be a part of emacs-elixir as it would require adding mmm-mode as a dependency, and there might be other multiple-mode-modes out there that some users might prefer for whatever reason.

I suggest that we add a section about how to get elixir-mode + markdown-mode working with mmm-mode to the emacs-elixir readme. That way users could add it to their configs using their preferred markdown- and multiple-mode-mode.

___
* Please correct me if I am wrong.

**Comment by lexmag** [comment]
Agree with @gausby. :+1:

**Comment by tonini** [comment]
As @gausby already mentioned, this is something which we shouldn't introduce into the `elixir-mode`.

**Comment by gausby** [comment]
Does anyone have an mmm-mode setup that works as described?

**Comment by rranelli** [comment]
When I have to write something more elaborate in the docs with markdown I just use `narrow-to-region` and change the major mode to `markdown`. 

When I'm done I get out of the narrowing and return to `elixir-mode`. The experience feels like editing code snippets in org with `org-edit-special`, and I'm pretty happy with it.

never used anything like mmm-mode though
