### ISSUE TITLE
No highlighting of ExUnit.Assertions Flunk

### ISSUE THREAD

**Issue by terakilobyte** [elixir-lang/emacs-elixir#306]
Very minor, but the syntax highlighting doesn't seem to be recognizing flunk as a function.

http://elixir-lang.org/docs/stable/ex_unit/ExUnit.Assertions.html#functions

https://www.dropbox.com/s/8ieunf8r2wtz5u4/Screenshot%202016-01-09%2008.35.15.png

**Comment by syohex** [comment]
`elixir-mode.el` does not highlight test module functions as below. So I wonder why you get such result. What configuration do you use ?

![saample](https://cloud.githubusercontent.com/assets/554281/12219312/1bb48f8e-b782-11e5-90ef-6ec4a18f4759.png)

**Comment by terakilobyte** [comment]
I'm using the elixir layer for spacemacs as well as alchemist. I was told by @tonini this was in `elixir-mode.el`, or perhaps I misunderstood. If so, no problem, I'll open the issue where appropriate!

**Comment by syohex** [comment]
@terakilobyte This is alchemist-test-mode issue. I have sent PR https://github.com/tonini/alchemist.el/pull/198. Please check it.

**Comment by terakilobyte** [comment]
Awesome, thanks! Closing this issue as I'm sure it'll get picked up soon.
