### ISSUE TITLE
Turn off default indentation by setting tab-stops

### ISSUE THREAD

**Issue by rvirding** [elixir-lang/emacs-elixir#308]
Is there any default way to turn off using tab stops to indent or must I do it by hand. It is generally a very bad way of doing it.

**Comment by tonini** [comment]
Hi @rvirding 

This is something you need to setup for Emacs in general.

https://www.gnu.org/software/emacs/manual/html_node/eintr/Indent-Tabs-Mode.html

**Comment by rvirding** [comment]
Yes, that I know. What I was trying to get at that changing the actual tab-stop sizes from the default 8 to 2, in this case, is a bad idea. Many things assume tab stops are 8 wide. It looks really weird when you forget to untabify and print the file. And you don't really need to either as it usually just works by the indent function returning how many steps it is to indent.

**Comment by tonini** [comment]
I think you want to have a look at this article about tabs and indentation
inside Emacs https://www.emacswiki.org/emacs/IndentationBasics

Robert Virding <notifications@github.com> schrieb am Do., 17. März 2016,
14:35:

**Comment by tonini** [comment]
Hi @rvirding 

Did you have success with the article above?

**Comment by rvirding** [comment]
I had no problem with the article I just want to point out that it does show some of the problems you get when changing the tab size. Try looking under where it said

And here for the other poor bastards:

    sub SmileyReplace {
    ________foreach my $regexp (keys %Smilies) {
    ________________if (m/\G($regexp)/cg) {
    ________________________return $q->img({-src=>$Smilies{$regexp}, -alt=>$1, -class=>'smiley'});
    ________________}
    ________}
    }

This what I want to avoid. And you don't need to set the actual tab size, emacs can do it anyway. Then let each user set indent-tabs-mode to nil so you only get spaces.

**Comment by tonini** [comment]
I'll close this issue for now because I think it has nothing directly to do with the `elixir-mode`. It's more a basic emacs setup thing.

**Comment by rvirding** [comment]
I don't agree as the elixir-mode explicitly uses setting tab stops. And I don't think it should, just because it makes things difficult for others.

**Comment by tonini** [comment]
Hi @rvirding 

I'll remove the `tab-width` setting we make in the `elixir-mode`.

Thanks for the report and the patience.

**Comment by tonini** [comment]
@rvirding 

https://github.com/elixir-lang/emacs-elixir/commit/981f11d9ff45d1dbad0bd4d9c73330397ce9c58f

**Comment by rvirding** [comment]
Thanks. It still works I hope. :-)

**Comment by tonini** [comment]
haha yes it does. ;-)

**Comment by rvirding** [comment]
Then I'm happy.
