### ISSUE TITLE
Char list heredoc breaks highlighting

### ISSUE THREAD

**Issue by lexmag** [elixir-lang/emacs-elixir#309]
Version: 20160103.54

<img width="315" alt="screen shot 2016-03-19 at 13 29 39" src="https://cloud.githubusercontent.com/assets/248290/13898603/c552099c-edd6-11e5-84f0-6c2c702593f9.png">

Sample file: https://github.com/elixir-lang/elixir/blob/c9b0bc8356760e646dbe27b6c82c3f7fff8e7cc9/lib/elixir/lib/module.ex.

**Comment by syohex** [comment]
How about following patch ?

```patch
diff --git a/elixir-mode.el b/elixir-mode.el
index a78b100..ddbb549 100644
--- a/elixir-mode.el
+++ b/elixir-mode.el
@@ -274,7 +274,7 @@ is used to limit the scan."
   (unless (elixir-syntax-in-string-or-comment-p)
     (let ((heredoc-p (save-excursion
                        (goto-char (match-beginning 0))
-                       (looking-at-p "~[sS]\"\"\""))))
+                       (looking-at-p "~[sS]\\(?:'''\\|\"\"\"\\)"))))
       (unless heredoc-p
         (forward-char 1)
         (let* ((start-delim (char-after (1- (point))))
```

Screenshot is here.

![triple-single-quote-sigil](https://cloud.githubusercontent.com/assets/554281/14013621/d3882898-f1f0-11e5-8959-440451ab6f30.png)

**Comment by tonini** [comment]
@syohex yes, this should make it. Could you open a PR for this one? :+1:

**Comment by syohex** [comment]
I have sent PR #314.

**Comment by tonini** [comment]
It's fixed thanks to @syohex :yellow_heart: 

Thanks @lexmag for the report :blue_heart:

**Comment by lexmag** [comment]
@syohex, @tonini thanks. :clap:
