### ISSUE TITLE
Heredoc indents incorrectly when it's the first thing in a do...end block

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/emacs-elixir#310]
Heredocs delimited with `"""` are indented incorrectly when they're the first thing inside a `do ... end` block (they're indented on the same level as the line that starts the `do`).

Current behaviour:

```elixir
def foo() do
"""
heredoc
"""
end

# or

for x <- [1, 2, 3] do
"""
heredoc
"""
end
```

Expected behaviour:

```elixir
def foo() do
  """
  heredoc
  """
end

# or

for x <- [1, 2, 3] do
  """
  heredoc
  """
end
```

**Comment by tonini** [comment]
Thanks @whatyouhide for the report, sorry it took so long. 💚 💛 💙 ❤️

**Comment by whatyouhide** [comment]
@tonini great job Samuel, never apologize for this stuff :)
