### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by AstonJ** [elixir-lang/emacs-elixir#312]
Hi, I am currently working on an Elixir theme, however, I can't seem to target string interpolation. I've tried both of the following in my theme but none of them work:

```
 '(font-lock-string-interpolation-face ((t (:foreground "#93B687"  ))))
 '(font-lock-interpolation-face ((t (:foreground "#93B687"  ))))
```

I've also used `what-cursor-position` (`C-u C-x` or `SPC u CTRL x =` in Spacemacs) but all I seem to get back is that it's just a normal variable.

Here's a screen grab - the theme (interpolation) should look like it does on the left (line 16):

https://files.gitter.im/syl20bnr/spacemacs/hTrE/Screen-Shot-2016-03-23-at-13.18.47.png

Am I doing something wrong or is this a bug?

**Comment by syohex** [comment]
elixir-mode uses `font-lock-variable-name-face` for string interpolation. And there are no `font-lock-string-interpolation-face` and `font-lock-interpolation-face`. You can check face at cursor by `M-: (face-at-point)`.

**Comment by AstonJ** [comment]
Hi @syohex, thanks for getting back to me.

Are there any plans to change it so it handles interpolation like the TextMate plug-ins do? (Which seems to be the same way the Ruby TM plugin does - as per the the screen grab at line 16).

No probs if not.

(Btw do you know how I can do `M-:` in Spacemacs please?)

**Comment by gausby** [comment]
@AstonJ `M-:` executes `eval-expression`. You can see the current keybinding by using the emacs help system called apropos, type `M-x apropos RET eval-expression`.
