### ISSUE TITLE
:: in binaries trigger atom highlighting

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/emacs-elixir#320]
Code like `<<foo::bar>>` highlights `foo:` as an atom, but it shouldn't.

**Comment by tonini** [comment]
@syohex could you please have a look at this? :heart_eyes:

**Comment by syohex** [comment]
I have send PR #321. Please check it.

**Comment by whatyouhide** [comment]
Closing this as it has been solved in #321.
