### ISSUE TITLE
Misindentation of tuples inside the "else" part of an "if" expression

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/emacs-elixir#328]
Tuples in the `else` part of an `if` expression are misindented as they're indented on the same level as the `else` keyword instead of one level more.

Current behaviour:

```elixir
if foo do
  :ok
else
{:tuple}
end
```

Expected behaviour:

```elixir
if foo do
  :ok
else
  {:tuple}
end
```

**Comment by utkarshkukreti** [comment]
This indents fine for me in `Elixir-Mode version: 2.2.9 (package: 20160413.7)`.

**Comment by whatyouhide** [comment]
I just pulled `master` and it's not working for me :confused:, I'll investigate further. If someone is able to reproduce this let us know :)

**Comment by gausby** [comment]
I just pulled master and I can confirm that this is the current behaviour:
```elixir
if foo do
  :ok
else
{:tuple}
end
```

**Comment by tonini** [comment]
It's fixed on master https://github.com/elixir-lang/emacs-elixir/commit/230b0dc9a7c9d95785ced03cbc99cb5509a84aff

Thanks for the report @whatyouhide :+1:

**Comment by whatyouhide** [comment]
Awesome @tonini, thanks so much :heart_decoration:
