### ISSUE TITLE
Module attributes with a comma break indentation for the rest of the file (sometimes)

### ISSUE THREAD

**Issue by manukall** [elixir-lang/emacs-elixir#336]
The following code breaks the indentation for the rest of the file:

```elixir
defmodule TestIndentation do
  import Enum
  @att %{ab: "cd",
         de: "fg"}
| <-- cursor is here
end
```

If I remove the `import Enum` line or the line-break after the comma, everything is fine.

Please let me know if I can help narrow this down further. I'm using spacemacs and everything is up to date, if that's relevant.

**Comment by utkarshkukreti** [comment]
For me, even the `@att` line is indented wrong:

Expected:

```elixir
defmodule TestIndentation do
  import Enum
  @att %{ab: "cd",
         de: "fg"}
  IO.inspect @att
end
```

Actual:

```elixir
defmodule TestIndentation do
  import Enum
@att %{ab: "cd",
       de: "fg"}
IO.inspect @att
end
```

**Comment by utkarshkukreti** [comment]
If I add a new line after `import Enum`, it works fine:

Expected and Actual:

```elixir
defmodule TestIndentation do
  import Enum

  @att %{ab: "cd",
         de: "fg"}
  IO.inspect @att
end
```

**Comment by tonini** [comment]
Thanks for the report guys 👍 

It's fixed on https://github.com/elixir-lang/emacs-elixir/commit/fc202762fd4e23ad1b5596b2a49fdce0cf6e3c23, just wait until melpa.org build the latest alchemist package from master before `package-install`usage.
