### ISSUE TITLE
"TODO:" comments appear to confuse indentation

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/emacs-elixir#341]
This is *extremely* weird 😄, and I have no idea if it happens specifically because of `elixir-mode`, but when I autoindent this:

```elixir
defmodule Foo do
  @initial_state %{
    socket: nil,
    opts: nil,
    # TODO: x,
    tail: "",
  }
end
```

it actually gets indented as:

```elixir
defmodule Foo do
  @initial_state %{
    socket: nil,
    opts: nil,
  # TODO: x,
  tail: "",
  }
end
```

I was able to reproduce this by launching Emacs with `emacs -Q` and then running:

```elisp
(package-initialize)
(add-to-list 'load-path "~/Code/emacs-elixir")
(require 'elixir-mode)
(elixir-mode)
```

I'm sorry in advance `elixir-mode` ends up not being the cause for this, but as far as my Emacs fu goes it appears so 😕

**Comment by tonini** [comment]
I'm on it :-)
