### ISSUE TITLE
Indentation of `with/1` with keywords

### ISSUE THREAD

**Issue by gausby** [elixir-lang/emacs-elixir#349]
There are some efforts to make indentation of `with/1` with keywords better in elixir-mode. Indentation is a question of personal preferences, but it would be good to know the myriad of ways one could indent a `with/1` in Elixir. Please use the following example to discuss indentation of the following example:
```elixir
with {:ok, width} <- Map.fetch(opts, :width),
  {:ok, height} <- Map.fetch(opts, :height),
  do: {:ok, width * height},
  else: {:error, :wrong_data}
```
Copy and paste the example and reply to this issue with your thinking on how to indent it. Below the line I will try (as fast as possible) to collect the solutions and give them a name a..z, so we can refer to them in discussion.

* * *
```elixir
# a
with {:ok, width} <- Map.fetch(opts, :width),
  {:ok, height} <- Map.fetch(opts, :height),
  do: {:ok, width * height},
  else: {:error, :wrong_data}

# b
with {:ok, width} <- Map.fetch(opts, :width),
     {:ok, height} <- Map.fetch(opts, :height),
  do: {:ok, width * height},
  else: {:error, :wrong_data}
```

**Comment by gausby** [comment]
```elixir
with {:ok, width} <- Map.fetch(opts, :width),
     {:ok, height} <- Map.fetch(opts, :height),
  do: {:ok, width * height},
  else: {:error, :wrong_data}
```

**Comment by whatyouhide** [comment]
Gave my answer in https://github.com/elixir-lang/emacs-elixir/pull/348.

```elixir
with pattern <- foo(),
     other_pattern <- bar(),
     last_pattern <- baz(),
  do: bong()
```

Also got a couple of thumbs up there, I'll mention them here as well 😃

**Comment by gausby** [comment]
@whatyouhide yeah, that is what I call *B*.

Your fine argumentation was that the `do:` (and `else:`) part stand out from the patterns, so they are easier to spot and (perhaps more importantly) not confuse with the patterns when reading the code—if I am paraphrasing correctly…

**Comment by whatyouhide** [comment]
@gausby yep, they separate patterns vs actions and after all it's the indentation that the Elixir documentation uses, so I'm strongly in favour of it.

**Comment by tonini** [comment]
Thanks a lot for this issue :)

What's the opinion about `with` used with parentheses? How should the identation behave in that case? Like a normal function call with a one level indentation on the next line until the end of the function call?

**Comment by whatyouhide** [comment]
@tonini I don't think `with()` is very common. People may be more inclined to do `(with ...)` if they want to wrap the expression in parens.

**Comment by aaronjensen** [comment]
Personally, I'm inclined towards A, but that's because I prefer the simplicity of always indenting the same (2 spaces) for everything everywhere, except for maybe in lisp languages, where I'm tending towards stockholm syndrome for the wild indentation rules that emacs applies.

**Comment by gausby** [comment]
@tonini I usually do all my `with/1`'s with parentheses like so;
```elixir
with(
  {:ok, width} <- Map.fetch(opts, :width),
  {:ok, height} <- Map.fetch(opts, :height),
  do: {:ok, width * height}
)
```
But I guess I will switch to something else when we can do do-blocks in the upcoming version of Elixir, and I guess I will prefer A when that is landed…because I already do stuff with weird indentation in function definitions, if I match on something like a map:
```elixir
def my_function(:subscribe, %{id: id,
                              message: message,
                              sender: sender}) do
  # ...
end
```
…perhaps a contrived example, but I actually like it ^_^
