### ISSUE TITLE
 _variables are highlighted if in a match

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/emacs-elixir#361]
Ignored variables (such as `_this`) are not highlighted like ignored variables if they're the left-hand side of a `=` match:

<img width="145" alt="screen shot 2016-05-27 at 12 19 09" src="https://cloud.githubusercontent.com/assets/3890250/15605281/3be5ebaa-2405-11e6-8ef2-586c3e704d0a.png">

<img width="62" alt="screen shot 2016-05-27 at 12 20 13" src="https://cloud.githubusercontent.com/assets/3890250/15605308/60d904f6-2405-11e6-8689-9ae9608a87f6.png">

(btw, I already expressed my opinion on this I think, but I really don't get why we highlight variables on the LHS of a match and only if they're the only thing on the LHS: we don't have assignment in Elixir, we only have pattern matching, so I don't think we should treat a patter with a single variable - that looks like an assignment - differently ¯\\\_(ツ)\_/¯)

**Comment by tonini** [comment]
@syohex 

Could you check this out? (I just ask because I know how good you are with these kind of syntax highlighting things 😏  )

>> Ignored variables (such as _this) are not highlighted like ignored variables if they're the left-hand side of a = match:

**Comment by tonini** [comment]
>> (btw, I already expressed my opinion on this I think, but I really don't get why we highlight variables on the LHS of a match and only if they're the only thing on the LHS: we don't have assignment in Elixir, we only have pattern matching, so I don't think we should treat a patter with a single variable - that looks like an assignment - differently ¯\_(ツ)_/¯)

@whatyouhide I'm feeling you :) Maybe open up a separate issue and we start discuss about this? 😏

**Comment by whatyouhide** [comment]
@tonini yes of course, let's discuss that in a separate issue. :)
