### ISSUE TITLE
smartparents setup error

### ISSUE THREAD

**Issue by mydearxym** [elixir-lang/emacs-elixir#362]
amazing work 

a warning occurs in  elixir-mode setup:

``` lisp
An error occurred while post-configuring smartparens in layer elixir (error: (void-function sp-with-modes))
```

**Comment by tonini** [comment]
Hi,

This has obviously nothing to do with the `elixir-mode`. You need to have a look at the spacemacs/elixir layer. It looks like `sp-with-modes` is called before the `smartparens` package is loaded like they fixed already for the ruby layer here -> https://github.com/syl20bnr/spacemacs/pull/4132

Thanks

**Comment by mydearxym** [comment]
thanks  @tonini 
i  simply comment the `smartparens` staff and use snippets instead
