### ISSUE TITLE
C-n and C-p do not preserve starting column

### ISSUE THREAD

**Issue by jimm** [elixir-lang/emacs-elixir#370]
When moving down/up lines with `C-n` and `C-p`, the starting column is not preserved. In other language modes, when you move vertically over a line that is shorter than your starting column, then to a line that is long again, the cursor goes back to the starting column.

If you start on the first line anywhere past the start of the line, then go down two lines via `C-n C-n`, you'll end up at the beginning of the third line instead of on the same column you were on on the first line.
```elixir
something |> something_else

something |> something_else
```

In many other languages modes (all the ones I've tried; I haven't tried them all, of course), you'd end up in the same column you started on.

**Comment by syohex** [comment]
I cannot reproduce this issue. Can you reproduce your issue by `emacs -Q -l /your_install_path/elixir-mode.el` ? Or did you enable `set-goal-column` ? If you enable `set-goal-column`, please disable it by `C-u M-x set-goal-column`. 

NOTE elixir-mode does not configure `C-n` and `C-p`.

**Comment by jimm** [comment]
Thank you for trying to reproduce this. You are correct: it doesn't happen when I start Emacs with an empty init file (I use Emacs for Mac OS X).

With my normal init `set-goal-column` is disabled, so I don't think that's it. When I visit any Elixir file the variable `goal-column` is nil. So that doesn't _seem_ to be the problem. Also the value of `line-mode-visual`, which can override `goal-column`, doesn't make a difference.

This is obviously a problem with my init (https://github.com/jimm/elisp), so I'm closing this ticket.
