### ISSUE TITLE
'end' insertion and indentation

### ISSUE THREAD

**Issue by 4ZM** [elixir-lang/emacs-elixir#372]
Writing this:
```elixir
defmodule Fubar do▯
```
and pressing enter, it would be nice to get:
```elixir
defmodule Fubar do
  ▯
end
```
The same goes for def:
```elixir
def fubar do▯
```
*enter*
```elixir
def fubar do
  ▯
end
```

**Comment by gausby** [comment]
I suggest that you solve this using a system like yasnippets or other code completion tools.

This package should only be for indentation and syntax highlighting.

**Comment by 4ZM** [comment]
Ok, thanks for the clarification

**Comment by 4ZM** [comment]
For posterity: https://github.com/hisea/elixir-yasnippets
