### ISSUE TITLE
Indentation with heredocs is less than ideal.

### ISSUE THREAD

**Issue by mattdeboard** [elixir-lang/emacs-elixir#86]
Indentation is not where I want it for `@doc` `@moduledoc` and `~s` syntax.

When pressing enter after a `"""`, I want the cursor to align with `@doc`:

```elixir
defmodule Foo.Bar do
  @moduledoc """
  X <--- cursor should align here automatically
  X <--- ditto
  """ # <-- ditto
```

Right now the cursor just goes to the beginning of the line (column 0) which is annoying. Thankfully however it can be manually aligned without interference from any auto-indentation busy-bodying.

**Comment by whatyouhide** [comment]
Any news on the indentation of heredocs?

**Comment by mattdeboard** [comment]
Related to #203
